### ISSUE TITLE
Latest AppLayout Body Has Unnecessary Space Below

### ISSUE THREAD

**Issue by ugurdoksan** [vaadin/vaadin-app-layout-flow#100]
Vaadin Version: **14.0.0.rc2**
Works fine in Mobile Browsers 👍 
Does **not** work in Web Browsers 👎 

![Untitled](https://user-images.githubusercontent.com/24225109/59468979-24e9e100-8e3c-11e9-85be-902f6be2cbe3.png)
![Untitled3](https://user-images.githubusercontent.com/24225109/59468980-27e4d180-8e3c-11e9-9241-d0a878deddd1.png)

**Comment by ugurdoksan** [comment]
![Untitled](https://user-images.githubusercontent.com/24225109/59469058-6e3a3080-8e3c-11e9-803e-430b2e8cac5c.png)

**Comment by ugurdoksan** [comment]
In the Dark Theme View
![Capture](https://user-images.githubusercontent.com/24225109/61170222-4db1e300-a56e-11e9-95f0-3d9387e32927.PNG)

**Comment by alvarezguille** [comment]
@ugurdoksan 
I wasn't able to reproduce this issue with rc2 nor rc4. Are you using `@Viewport` or some shared styles for the body or the main view? Can you reproduce it Chrome?

Can you add simple example to reproduce this issue?

**Comment by ugurdoksan** [comment]
@alvarezguille
I find the problem was about **@BodySize** annotation. It was giving a fixed size.
Thanks for your concern.
