### ISSUE TITLE
Usage with RouterLink

### ISSUE THREAD

**Issue by heruan** [vaadin/vaadin-app-layout-flow#11]
It's not clear how this component deals with `RouterLink`. It has a new `RoutingMenuItem` which takes a string as a route, but in Flow there is a `RouterLink` component which already takes care of that.

As a user approaching to use `AppLayout`, this causes me confusion.

**Comment by davidm76** [comment]
+1

**Comment by tulioag** [comment]
@heruan, `RoutingMenuItem` has been removed in favor of `AppLayoutMenuItem`. `AppLayoutMenu` is our default implementation for the menu, and it is using tabs in the same way, but now you can put any component on the menu slot. Here is an example with router links:
```java
        AppLayout layout = new AppLayout();
        RouterLink link1 = new RouterLink("Page 1",Page1.class);
        RouterLink link2 = new RouterLink("Page 2",Page2.class);
        RouterLink link3 = new RouterLink("Page 3",Page3.class);
        layout.setMenu(new HorizontalLayout(link1,link2,link3));
```
