### ISSUE TITLE
Applayout Scroll Feature Does Not Work In Mobile Landscape Mode

### ISSUE THREAD

**Issue by ugurdoksan** [vaadin/vaadin-app-layout-flow#112]
**Vaadin Version:** 14.0.3
**Device:** Samsung S9 Plus
**Browser:** Chrome with the latest version
**PWA:** Active
**Code:** Same with the demo code for Applayout with the latest version. I used Tabs with RouterLink. There is not any other unnecessary code.

Portre mode => OK 👍 
Landscape mode => NOT OK 👎 

Here are the screenshots below:

![PortreMode](https://user-images.githubusercontent.com/24225109/64337933-164d3900-cfe9-11e9-94b4-41683ed7980f.jpg)

![LandscapeMode](https://user-images.githubusercontent.com/24225109/64337945-1a795680-cfe9-11e9-8a31-005513868152.jpg)

**Comment by web-padawan** [comment]
Thanks for the issue and sorry about leaving it without a response.

There is now issue in the web component so I'm closing this one.
We will implement a proper fix in vaadin/vaadin-app-layout#127
