### ISSUE TITLE
calling setIcon on DrawerToggle doesn't update its icon

### ISSUE THREAD

**Issue by OlliTietavainenVaadin** [vaadin/vaadin-app-layout-flow#117]
It should be possible to change the icon of the DrawerToggle by calling `drawerToggle.setIcon(some icon)`.

**Comment by web-padawan** [comment]
Note: there might be changes needed also because `setIcon` uses either "prefix" or "suffix" slots (vaadin/vaadin-button-flow#133), but DrawerToggle only has a default unnamed slot.

**Comment by ivanooi** [comment]
I had tried that in Vaadin 15. I cant change the icon. not working..

        DrawerToggle toggle = new DrawerToggle();
        
        toggle.setIcon(icon);
        toggle.setId("menu-toggle");
        addToNavbar(toggle);
