### ISSUE TITLE
open drawer programmaticaly

### ISSUE THREAD

**Issue by tJeyhun** [vaadin/vaadin-app-layout-flow#136]
Hi,

My root view is :

    class MainView extends AppLayout implements BeforeEnterObserver

in `beforeEnter` I add and remove some components to drawer depending on the route. Some routes do not have sub-components which lead to an empty drawer. In such cases, I hide drawer `setDrawerOpened(false)`. It works.
But when I switch from such empty route to route with some components in drawer `setDrawerOpened(true)` does not work. I must explicitly click drawerToggle button to open 
drawer. 'setDrawerOpened( !isDrawerOpened() )' does not work either. I have tried to run last code from different places (button, menu) but it does not work. Drawer gets closed properly but does not opens.

Using Vaadin 14.1.21 
tested on latest Firefox and Chrome

**Comment by syampillai** [comment]
Same issue in Vaadin 15.0.5 too.
On the AppLayout component, setDrawerOpened(true) doesn't open the drawer even though the status isDrawerOpened() is set to "true".

**Comment by nicoulaj** [comment]
After upgrading from Vaadin 14.1.25 to 15.0.5, the drawer toggle does not work for me anymore. I can set the drawer open or closed in the main view constructor, but not change it after. I can see no Javascript error, the click event reaches server side, and `isDrawerOpened()` changes.

**Comment by tomivirkki** [comment]
Workaround:

Use
```java
getElement().setProperty("drawerOpened", opened);
```
instead of
```java
setDrawerOpened(opened)
```
