### ISSUE TITLE
No API to replace the menu slot content

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-app-layout-flow#20]
The component makes a hard assumption about the use cases of itself and limits how to use it.

For example, a common use case is to place a global search field in the center area of the navbar, like in many Google apps (Drive, Inbox).

This is probably possible using the lower-level Element API like this (not sure if this works for real):

```java
appLayout.getElement().removeChild(appLayout.getMenu().getElement());
TextField search = new TextField();
search.getElement().setAttribute("slot", "menu");
appLayout.getElement().appendChild(search.getElement());
```

I’m not sure if this an acceptable solution, or does it have some drawbacks compared to a properly supported API?

**Comment by tulioag** [comment]
@jouni , I created a pull request to address this issue ( #36 ). Any feedback would be appreciated.

**Comment by jouni** [comment]
I’m not sure if I’m the right person to give feedback about those changes. @Artur- might be better, or someone else who is more aware of how Flow developers would expect things to work.

My initial reaction was that it’s a good move to extract the menu functionality out of the layout component (so that it’s closer to 1:1 mapping between the web component). But then I’m not sure if the concept(s) of the `AppLayoutMenu` is properly thought out as something we want to maintain in the future.
