### ISSUE TITLE
It should be possible to provide a custom AppLayoutMenu to a AbstractAppRouterLayout subclass

### ISSUE THREAD

**Issue by Artur-** [vaadin/vaadin-app-layout-flow#56]
It would be easy to hide away the implementation for #55 in a custom `AppLayoutMenu` class but it does not seem possible to get `AbstractAppRouterLayout` to use one. If there was an optional protected constructor accepting `AppLayout` and/or `AppLayoutMenu`, this would be possible

**Comment by tulioag** [comment]
AppLayoutMenu is gone and any component can be added directly to the drawer.
