### ISSUE TITLE
I expect AppLayout to be simpler to use as my main layout

### ISSUE THREAD

**Issue by johannesh2** [vaadin/vaadin-app-layout-flow#58]
I downloaded a project base and the first thing I did to the MainView class was I added ´extends AppLayout´ I expected to start working there and add menu items. Instead, I needed to call createMenu() and work with the return value of it. Later I noticed there is an abstract base class I was supposed to use for my router layout. I think AppLayout should be already implementing RouterLayout, right?

**Comment by tulioag** [comment]
Fixed in https://github.com/vaadin/vaadin-app-layout-flow/pull/72
