### ISSUE TITLE
AbstractAppRouterLayout and @HtmlImport

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/vaadin-app-layout-flow#61]
@stefanuebe commented on [Mon Dec 10 2018](https://github.com/vaadin/flow/issues/4843)

### Description
It seems like the `@HtmlImport` annotation is ignored for `AbstractAppRouterLayout` subclasses. I tried to load custom styles as usual by adding the annotation, but the import is not added to the dom. When using a plain router layout, everything works as expected.

### Sources
``` 
@HtmlImport("frontend://styles/styles.html")
public class ApplicationRouterLayout extends AbstractAppRouterLayout {
   ...
}
```

```
@HtmlImport("frontend://styles/styles.html")
public class PlainRouterLayout extends VerticalLayout implements RouterLayout {
   ...
}
```

```
<link rel="import" href="../bower_components/polymer/lib/elements/custom-style.html">

<custom-style>
    <style>
        html {
            --lumo-primary-color: red !important;
        }
    </style>
</custom-style>
```

### Workaround
The html import can be set by using an attachListener for the appLayout instance in the configuration methd.

```
public class MainLayout extends AbstractAppRouterLayout {
    @Override
    protected void configure(AppLayout appLayout, AppLayoutMenu menu) {
        appLayout.addAttachListener(event -> {
            event.getUI().getPage().addHtmlImport("frontend://styles/styles.html");
        });
        ...
    }
    ...
}


```

---

@denis-anisimov commented on [Thu Dec 13 2018](https://github.com/vaadin/flow/issues/4843#issuecomment-446903770)

What is ` AbstractAppRouterLayout` ?
Flow doesn't have such class. 
Do you use a wrong project for the issue ?

---

@stefanuebe commented on [Thu Dec 13 2018](https://github.com/vaadin/flow/issues/4843#issuecomment-446961031)

Full class name is com.vaadin.flow.component.applayout.AbstractAppRouterLayout (implements RouterLayout). It is used in the Bakery Starter.

---

@denis-anisimov commented on [Thu Dec 13 2018](https://github.com/vaadin/flow/issues/4843#issuecomment-446961410)

> It is used in the Bakery Starter.

Very good.
Then this should go to the bakery stater.

**Comment by tulioag** [comment]
Hi @stefanuebe. I moved the issue to this repository. AbstractAppRouterLayout is part of Vaadin App Layout.

**Comment by Artur-** [comment]
This really makes it inconvenient to use it as a router layout as you cannot load a `shared-styles.html` using `@HtmlImport` on the class. The reason for the problems is that the class does not extend `Composite` as it should but instead makes a half-way custom implementation of a composite

**Comment by tulioag** [comment]
Solved in https://github.com/vaadin/vaadin-app-layout-flow/pull/72
